
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build .Net projects
  inputs:
    command: build
    projects: 'CICDTest.sln'
    arguments: --configuration $(buildConfiguration)
    workingDirectory: '$(Build.SourcesDirectory)'

- task: DotNetCoreCLI@2
  displayName: Publish Bearing User
  inputs:
    command: publish
    projects: 'CICDTest.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/CICDTest'
    workingDirectory: '$(Build.SourcesDirectory)/CICDTest/'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
